# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp 
#' @description A Gibbs sampler using Rcpp
#' @param n the number of sample
#' @param n1 the number of between-sample random numbers
#' @param a a constant
#' @param b a constant
#' @return a random sample of size n
#' @importFrom stats rbinom rbeta 
#' @examples
#' \dontrun{
#' n <- 1e4 #length of chain
#' a <- 2
#' b <- 2
#' n1=10
#' mtrix <- matrix(0,n,2)
#' mtrix <- gibbsC(n,n1,a,b)
#' } 
#' @export
NULL

gibbsC <- function(n, n1, a, b) {
    .Call('_StatComp21052_gibbsC', PACKAGE = 'StatComp21052', n, n1, a, b)
}

